# run tmux when kitty is opened up
shell tmux

# ===General===
enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no

# hide_window_decorations yes
# hide_window_decorations titlebar-only
hide_window_decorations titlebar-and-corners
window_margin_width 0
placement_strategy center
window_border_width 0

remember_window_size no
initial_window_width 100c
initial_window_height 35c

scrollback_lines 10000

clipboard_control write-clipboard write-primary read-clipboard read-primary  # Better clipboard integration
open_url_with default  # Open URLs with your default browser
copy_on_select yes     # Auto-copy selected text (like browser behavior)

shell_integration no-cursor # Disable some shell integrations (faster)
startup_session none # Don't auto-restore sessions (tmux handles this)

cursor_blink_interval 0
# cursor_shape block
cursor_beam_thickness 2.5
cursor_shape beam
# cursor_shape underline
cursor_shape_unfocused unchanged

# ===Fonts===
# font_family Inconsolata Bold Nerd Font Complete Mono
# font_family Roboto Mono Bold Nerd Font Complete Mono
font_family Roboto Mono Nerd Font Complete

bold_font auto
italic_font auto
font_size 16.0


# ===Themes===
# include ~/.config/kitty/kitty-themes/themes/Solarized_Dark.conf
# include ~/.config/kitty/kitty-themes/themes/Solarized_Darcula.conf
include ~/.config/kitty/kitty-themes/themes/Solarized_Dark_Higher_Contrast.conf
# include ~/.config/kitty/kitty-themes/themes/Solarized_Light.conf

# ===Keymaps===
map F11 toggle_fullscreen
